#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "litecart"
name = "Litecart"

description.en = "Super simple online store"
description.fr = "Boutique en ligne super simple"

version = "0.1.12~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
admindoc = "https://github.com/shurco/litecart?tab=readme-ov-file#adding-payment-systems"
code = "https://github.com/shurco/litecart"

[integration]
yunohost = '>= 11.2'
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true
ldap = false
sso = true
disk = "25M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]       

        amd64.url = "https://github.com/shurco/litecart/releases/download/v0.1.12/litecart_0.1.12_linux-amd64.tar.gz"
        amd64.sha256 = "0c32707c2c3459c207c2aeaae270415daf03d80ebc64fa0f1a4c67687723dfa2"
        arm64.url = "https://github.com/shurco/litecart/releases/download/v0.1.12/litecart_0.1.12_linux-arm64.tar.gz"
        arm64.sha256 = "a9efe60870d18a18e061a4b3f6eb2870fd401a901b92defb1db10f132b35c315"
        in_subdir = false

        autoupdate.asset.amd64 = "litecart_.*linux-amd64.tar.gz$"
        autoupdate.asset.arm64 = "litecart_.*linux-arm64.tar.gz$"
        autoupdate.strategy = "latest_github_release"

[resources.system_user]

[resources.install_dir]

[resources.permissions]
main.url = "/"

[resources.ports]
