#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "litecart"
name = "Litecart"
description.en = "Lightweight and customizable e-commerce"
description.fr = "E-commerce léger et personnalisable"

version = "2.6.3~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "CC-BY-NC-ND-4.0"
website = "https://www.litecart.net/"
demo = "https://www.litecart.net/demo"
userdoc = "https://www.litecart.net/wiki/"
admindoc = "https://www.litecart.net/wiki/introduction"
code = "https://github.com/litecart/litecart"
cpe = "cpe:2.3:a:litecart:litecart"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin_username]
    ask.en = "The name for your Litecart admin account."
    ask.fr = "L'identifiant pour votre compte d'administration Litecart."
    type = "string"

    [install.admin_password]
    ask.en = "The password for your Litecart admin account."
    ask.fr = "Le mot de passe pour votre compte d'administration Litecart."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Wachhund/litecart/archive/refs/heads/fix/cli-installer-paths.tar.gz"
    sha256 = "75a4fd407f0e72ecdc64fe596bdd690d28447d737b4dc60edac58cf1f58d4ff4"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-apcu php8.3-curl php8.3-dom php8.3-gd php8.3-imagick php8.3-mysql php8.3-simplexml php8.3-mbstring php8.3-intl php8.3-zip php8.3-xml"

    [resources.database]
    type = "mysql"
