#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  alias __INSTALL_DIR__/public_html/;

  index index.php;

  client_max_body_size 500M;

  rewrite ^/(cache|images)/ /$request_uri last;

  try_files $uri $uri/ /index.php$is_args$args;

  location ~ [^/]\.php(/|$) {
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;

    include fastcgi_params_no_auth;

    fastcgi_param MOD_REWRITE  On;   # Enables LiteCart's URL rewriting
  }

  # See: https://www.litecart.net/fr/wiki/how_to_run_litecart_on_nginx

  # Return 404 for hidden files and directories starting with .
  location ~ /\. {
    return 404;
  }

  # Return 404 for specific extensions
  location ~ \.(htaccess|htpasswd|inc\.php|log|sql|bak|backup|old|tmp|env|conf|config)$ {
    return 404;
  }

  # Deny access to some storage directories
  location ~ ^/(data|logs|vendor|vmods)/ {
    deny all;
  }

  # CORS header for loading for font files
  location ~* \.(eot|ttf|otf|woff|woff2)$ {
    add_header Access-Control-Allow-Origin "*" always;
  }

  # Static content cache and compression
  location ~ .(a?png|avif|bmp|css|eot|gif|ico|jpe?g|jp2|js|otf|pdf|svg|tiff?|ttf|webp|woff2?)$ {
    expires 2w;
    gzip_static on;
  }

}
