#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version 0.8.3.

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..."

ynh_change_url_nginx_config

#=================================================
# MODIFY URL IN SYSTEMD CONF
#=================================================

ynh_add_systemd_config

ynh_systemd_action --service_name="$app" --action="restart" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last