#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# TODO

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================

ynh_script_progression "Finalizing installation..."

pushd "$install_dir"
ynh_exec_as_app php$php_version install.php \
    --document_root="$install_dir/public_html" \
    --db_server="127.0.0.1" \
    --db_database="$db_user" \
    --db_username="$db_user" \
    --db_password="$db_pwd" \
    --db_collation="utf8mb4_unicode_520_ci" \
    --admin_folder="manage" \
    --admin_username="$admin_username" \
    --admin_password="$admin_password"
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
